/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tde1;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("~ Pilha ~");

        var pilha = new Pilha(3);
        pilha.insere(5);
        pilha.insere(10);
        pilha.insere(20);
        pilha.imprime();
        assert pilha.cheia();

        pilha.remove();
        pilha.remove();
        pilha.imprime();
        assert !pilha.cheia() && !pilha.vazia();

        pilha.remove();
        assert pilha.vazia();

        System.out.println("~ Fila ~");

        var fila = new Fila(3);

        fila.insere(5);
        fila.insere(10);
        fila.insere(20);
        fila.imprime();
        assert fila.cheia();

        fila.remove();
        fila.remove();
        fila.imprime();
        assert !fila.cheia() && !fila.vazia();

        fila.remove();
        assert fila.vazia();
    }
}
